# azure-pipelines.yml

trigger:
- main
pool:
  vmImage: windows-2019
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  subscription: 'AOPDemo'
  artifactName: 'drop'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'AOPDemo'
        KeyVaultName: 'aopdemo-dev'
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >-
          /p:DeployOnBuild=true 
          /p:WebPublishMethod=Package 
          /p:PackageAsSingleFile=true 
          /p:SkipInvalidConfigurations=true 
          /p:PackageLocation="$(Build.ArtifactStagingDirectory)"
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: $(artifactName)
        publishLocation: 'Container'

- stage: DEV
  dependsOn: Build
  variables: 
    Environment: $(Environment-DEV)
  jobs:
  - template: deploy-appservice-template.yml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: dape-azure-app-service-dev
      subscription: $(subscription)

- stage: QA
  dependsOn: DEV
  variables: 
    Environment: QA
  jobs:
  - template: deploy-appservice-template.yml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: dape-azure-app-service-qa
      subscription: $(subscription)

- stage: STAGE
  dependsOn: QA
  variables: 
    Environment: STAGE
  jobs:
  - template: deploy-appservice-template.yml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: dape-azure-app-service-stage
      subscription: $(subscription)

- stage: PROD
  dependsOn: STAGE
  variables: 
    Environment: PROD
  jobs:
  - template: deploy-appservice-template.yml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: dape-azure-app-service-prod
      subscription: $(subscription)